# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Unacast Labs
tagline:             'Tech blog'
description:         'Made with &#9829; by <a href="http://unacast.com">Unacast</a>'
url:                 http://unacast.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Unacast
  url:               https://twitter.com/unacast
  email:             hello@unacast.com
